### ISSUE TITLE
Namespace the org sandbox space quota

### ISSUE THREAD

**Issue by jbarnicle** [18F/cg-sandbox-bot#18]
Right now when we create a sandbox space guota for an org, we create it with generic name of `sandbox-quota`, while creating the actual sandbox space with a qualified name of `sandbox-{domain}`  for example - `sandbox-gsa`.  I think it would be a good idea for consistency sake, and to eliminate confusion when browsing space quotas in the admin ui (or any other tool) that we qualify the sandbox space quota names with the domain - perhaps `sandbox-gsa-space-quota`

Thoughts? @dlapiduz @LinuxBozo

**Comment by jmcarp** [comment]
Moving to a single sandbox org, so we don't need to do this.
