### ISSUE TITLE
If the bot sees anyone with a .gov or .mil it should create a sandbox space for them

### ISSUE THREAD

**Issue by dlapiduz** [18F/cg-sandbox-bot#5]
The current way things work is the following:
- Sandbox bot monitors UAA for new users
- If a new user is found and it matches a domain in the `DOMAINS` env variable (which looks something like this: `[{"domain": "foo.gov", "space":"sandbox-foo", "guid":"123-222-222", "space_quota_guid": "333"}]" it continues to create a space
- The bot creates a space with the "username" of the email address (dlapiduz out of dlapiduz@github.io) in the "sandbox-foo" organization
- The bot assigns that space a space quota to the space quota with 333 guid

The way we need things to work:
- Sandbox bot monitors UAA for new users
- If a new user is found and has a .gov or .mil address it continues to create a space
- The bot checks if there is an org with the main domain of the email address `foo.bar.gov` would check `sandbox-bar`
- If the org doesn't exist, it creates it and creates a space quota to match
- The bot creates a space with the "username" of the email address (dlapiduz out of dlapiduz@github.io) in the "sandbox-foo" organization
- The bot assigns that space a space quota to the space quota for the organization

**Comment by jbarnicle** [comment]
@dlapiduz - Just looking for a little clarification on a couple of points.

For users with a .gov or .mil address, are we still requiring that they match a domain in the `DOMAINS` Env variable?  When we create the user space, we pull the quota guid from the setting domain setting.

`space_quota_definition_guid: domain["space_quota_guid"]`

If we are not requiring that the domain be present, we will need a guid for that (unless you literally meant the guid should be 333).

In the new version, we will still monitor users in the existing fashion - the exception is that for users with a .gov or .mil address, if there isn't an existing `sandbox-xxx` organization for that user, we will create that sandbox - and then subsequently add that user to the newly created `sandbox-xxx` org.   Both the sandbox and user `space_quota_definition_guid`s will be pulled from the value in the `DOMAINS` env variable.

**Comment by dlapiduz** [comment]
@jbarnicle the idea is to get rid of the `DOMAINS` env var... That way we don't whitelist people, we create a sandbox for everyone with a .gov/.mil.

You can find the space quota by name. We just create the quota called `sandbox_quota`, that way we don't have to keep track of things.

> In the new version, we will still monitor users in the existing fashion - the exception is that for users with a .gov or .mil address, if there isn't an existing sandbox-xxx organization for that user, we will create that sandbox - and then subsequently add that user to the newly created sandbox-xxx org. Both the sandbox and user space_quota_definition_guids will be pulled from the value in the DOMAINS env variable.

This seems accurate.

**Comment by jbarnicle** [comment]
@dlapiduz I think this issue has been fixed.  Can you close?

**Comment by afeld** [comment]
Pretty positive this is done...feel free to re-open if that's not the case!
